# Sample .travis.yml for R projects

language: c
sudo: required

env:
  global:
   - secure: "Ha9NmkMT0qV/j5LKvAnkAGDsSrIZFudaIMIJNd0xy2lePOH89lna5OTU1PnNnaayeMmaarwr5/Cz4WE8ZycGFKJxoErQEfQ2/UvNY+X+wPH1mXUj0XsyBNklE55j2Y5Co6jssFy7sxWEX4fx5cWASu4tSUfmoDUHudBRQ0DkQbo="

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - export BOOTSTRAP_PANDOC="1"
  - export BOOTSTRAP_LATEX="1"
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install
  - ./travis-tool.sh r_binary_packages knitr
  - ./travis-tool.sh r_binary_packages dplyr
  - ./travis-tool.sh r_binary_packages ggplot2
  - ./travis-tool.sh r_binary_packages rmarkdown

script:
  - PATH="${PATH}:/home/travis/opt/pandoc"
  - echo $PATH
  - ls /home/travis/opt/pandoc
  - which pandoc
  - make

after_success:
  - cat handout-script.R
