# Sample .travis.yml for R projects

language: c
sudo: required

env:
  global:
   - secure: "Ha9NmkMT0qV/j5LKvAnkAGDsSrIZFudaIMIJNd0xy2lePOH89lna5OTU1PnNnaayeMmaarwr5/Cz4WE8ZycGFKJxoErQEfQ2/UvNY+X+wPH1mXUj0XsyBNklE55j2Y5Co6jssFy7sxWEX4fx5cWASu4tSUfmoDUHudBRQ0DkQbo="

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - export BOOTSTRAP_PANDOC=1
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install
  - ./travis-tool.sh r_binary_install knitr dplyr ggplot2 rmarkdown RSQLite

script:
  - make clean
  - make

after_success:
  - export GH_REPO="@github.com/fmichonneau/R-ecology.git"
  - export FULL_REPO="https://${GH_TOKEN}${GH_REPO}"
  - echo ${FULL_REPO}
  - git config user.name "fmichonneau"
  - git config user.email "francois.michonneau@gmail.com"
  - ls
  - ls .git
  - git status
  - git add *.html
  - git commit -m "update html pages"
  - git push ${FULL_REPO} HEAD:gh-pages
  - cat handout-script.R
